### ISSUE TITLE
LongNumber::impl::comparison bug

### ISSUE THREAD

**Issue by giulianoassaggio** [giulianoassaggio/LongNumber#3]
The function compares the absolute values, but if both numbers are negative, the result should be inverted:
for example, is true that 15 > 12, but is false that (-15) > (-12)

see: https://github.com/giulianoassaggio/LongNumber/blob/37c5fd74881ef72bcd91aba3d550328fe2f2b2a1/src/Implementation/LongNumber_Comparisons.cpp#L7

**Comment by manhtoanbkhn** [comment]
Hello, thank for your work. I'm very excited about this project so I would like to solve this bug.

**Comment by manhtoanbkhn** [comment]
Hi @giulianoassaggio , I already opened a PR for this issue. Can you review it? Btw, I'd be honored to implementing other features to complete the lib. Is there any plan?

**Comment by giulianoassaggio** [comment]
Hi, PR merged, thank you! I didn't even notice "next" instead of "prev", glad you fixed it.
the library is open source, you can implement whatever you want, any improvement is welcome :).
By the way, i know that @dadezz is checking some mistakes i made in constructors, hope he'll let us know with a PR soon
